config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"
  

  resources :semesters, only: [:new, :create ]

  namespace :zno do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  namespace :distant do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  devise_for :users

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_and_belongs_to_many :subjects, -> { uniq }
	has_many :task_reports
	validates :email, presence: true
	validates :first_name, presence: true
	default_scope { order(:last_name => :asc)}

	def self.find_by_subject subject
		joins(:subjects).where("subjects.title = ?", subject)
	end


	def self.send_task_for_subject subject
		students = self.find_by_subject subject
		task = Task.first
		students.each do |student|
			TaskMailer.send_task(task, student).deliver
		end
	end

	def full_name
		"#{last_name} #{first_name} "
	end

	def subject_titles
		subjects.pluck(:title).join(", ")
	end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_and_belongs_to_many :students, -> { uniq }
	
end

app/controllers/distant/mails_controller.rb
class Distant::MailsController < DistantController

	def index
		@tasks = Task.where(grade: "distant", semester: @semester.name)
		@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
		if params[:format]
			@current_task = Task.find_by_id params[:format]
			@task_reports =@current_task.task_reports.includes(:student)
		else
			@task_reports = TaskReport.where.not(grade: "11")
		end
	end

	def send_task
		@tasks = Task.where(grade: "distant", semester: @semester.name)
		@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
	end

	def send_mail
		@task  =Task.find_by_id params[:task][:id]
		@subject = Subject.find_by_id params[:subject][:id]
		task_reports, threads =[], []
		@subject.students.where(semester: @semester.name).where.not(grade: "11").each do |student|
			threads << Thread.new do
				TaskMailer.send_task(@task, student).deliver
				task_report = TaskReport.new(task: @task, student: student, grade: student.grade)
				task_report.save
				ActiveRecord::Base.connection.close
			end
		end

		threads.each &:join
		redirect_to distant_mails_index_path
	end

	def receive
		task = Task.find_by_id params[:task][:id]
		@task_reports = task.task_reports
		emails = Mail.all.select { |email| email.subject.include? task.title }
		threads = []
  		emails.each do |email|
  			threads << Thread.new do 
	  			task_report = @task_reports.joins(:student).where("students.email = ?", email.from.first).first
	  		
	  			if task_report
	  				task_report.status =  1
	  				attachment = email.attachments.first
	  				if attachment
		  				file = StringIO.new(attachment.decoded)
		  				file.class.class_eval { attr_accessor :original_filename, :content_type }
		  				file.original_filename = attachment.filename
		  				file.content_type = attachment.mime_type
		  				task_report.report_file = file
		  			end
		  			task_report.save
	  			end
	  			ActiveRecord::Base.connection.close
	  		end
  		end
  		threads.each &:join
		redirect_to distant_mails_index_path(task)
	end

	def download_report

		tr = TaskReport.find_by_id(params[:report_id])
		send_file(tr.report_file.path , filename: tr.report_file_file_name, type: tr.report_file_content_type)
	end


	protected


end

app/controllers/distant/students_controller.rb
class Distant::StudentsController < DistantController

	def new
		@student = Student.new
		@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
	end

	def create
		@student = Student.new student_params
		@student.semester = @semester.name
		subjects = Subject.where(id: params[:subject_ids])
		subjects.each do |subject|
			@student.subjects << subject
		end

		if @student.save
			redirect_to distant_students_path
		else
			render 'new'
		end
	end

	def edit
		@student = Student.find params[:id]
		@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
	end

	def update
		@student = Student.find params[:id]
		subjects = Subject.where(id: params[:subject_ids])
		subjects.each do |subject|
			@student.subjects << subject
		end
		@student.update student_params
		if @student
			redirect_to distant_students_path
		else
			render 'edit'
		end
	end

	def index
		unless params[:student_ids]
			@students = Student.where(semester: @semester.name).where.not(grade: "11")
			@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика"])
			@student_ids = @students.map {|s| s.id }
		else
			@students = Student.where(id: params[:student_ids])
			@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
			@student_ids = params[:student_ids]
		end
	end

	def show

	end

	def filter
		if params[:subject][:id].present?
			@students = Student.joins(:subjects).where("semester = ? and subjects.id = ?",@semester.name, params[:subject][:id]).where.not(grade: "11")
			@student_ids = @students.map { |s| s.id }
		else
			@students = Student.where(semester: @semester.name).where.not(grade: "11")
			@student_ids = @students.map {|s| s.id }
		end
		@subjects = Subject.where(title: ["Математика","Химия","Биология","Физика", "Информация"])
		render 'index'
	end

	def delete
		@student = Student.find(params[:student_id])
	end

	def destroy
     	@student = Student.find(params[:id])
     	@student.destroy
     	redirect_to distant_students_path(student_ids: params[:student_ids])
	end

	def xls_index
		package = Axlsx::Package.new
   		workbook = package.workbook
    	@students = Student.where(id: params[:student_ids])
    	workbook.add_worksheet(name: "Студенты") do |sheet|
     		sheet.add_row ["ФИО Студента", "Email", "Адрес", "Skype","Телефон","Школа" ,"Класс","Предметы"]
     		@students.each do |s|
     			subjects = s.subjects.map { |s| s.title}.join(", ")
        		sheet.add_row [s.full_name, s.email, s.address, s.skype ,s.phone, s.school,s.grade, subjects]
      		end
    	end
    	package.serialize "Basic.xlsx"
    	send_file("#{Rails.root}/Basic.xlsx", filename: "Basic.xlsx", type: "application/vnd.ms-excel")
	end

	protected 
		def student_params
			params.require(:student).permit(:first_name, :last_name, :email, :phone, :address, :school, :grade, :skype)
		end
end

app/controllers/distant/tasks_controller.rb
class Distant::TasksController < DistantController
  def new
  	@task = Task.new
  end

  def index
  	@tasks = Task.where(grade: "distant", semester: @semester.name)
  end

  def create
  	@task = Task.new task_params
    @task.grade = "distant"
    @task.semester = @semester.name
    @task.save
  	redirect_to  distant_tasks_path
  end

  protected

  	def task_params
 	 params.require(:task).permit(:title, :task_file)
	end
end

app/controllers/distant_controller.rb
class DistantController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def new
		@student = Student.new
		@subjects = Subject.all
	end

	def create
		@student = Student.new student_params
		subjects = Subject.where(id: params[:subject_ids])
		subjects.each do |subject|
			@student.subjects << subject
		end

		if @student.save
			redirect_to students_path
		else
			render 'new'
		end
	end

	def index
		@students = Student.all
		@subjects = Subject.all
		@student_ids = @students.map {|s| s.id }
	end

	def show

	end

	def filter
		if params[:subject][:id].present?
			@students = Student.joins(:subjects).where("subjects.id = ?", params[:subject][:id])
			@student_ids = @students.map { |s| s.id }
		else
			@students = Student.all
			@student_ids = @students.map {|s| s.id }
		end
		@subjects = Subject.all
		render 'index'
	end

	def xls_index
		package = Axlsx::Package.new
   		workbook = package.workbook
    	@students = Student.where(id: params[:student_ids])
    	workbook.add_worksheet(name: "Студенты") do |sheet|
     		sheet.add_row ["ФИО Студента", "Email", "Адрес", "Телефон","Школа" ,"Предметы"]
     		@students.each do |s|
     			subjects = s.subjects.map { |s| s.title}.join(", ")
        		sheet.add_row [s.full_name, s.email, s.address, s.phone, s.school, subjects]
      		end
    	end
    	package.serialize "Basic.xlsx"
    	send_file("#{Rails.root}/Basic.xlsx", filename: "Basic.xlsx", type: "application/vnd.ms-excel")
	end

	protected 
		def student_params
			params.require(:student).permit(:first_name, :last_name, :email, :phone, :address, :school)
		end
end

app/controllers/zno/students_controller.rb
class Zno::StudentsController < ZnoController

	def new
		@student = Student.new
		@subjects = Subject.all
	end

	def create
		@student = Student.new student_params
		@student.grade = "11"
		@student.semester = @semester.name
		subjects = Subject.where(id: params[:subject_ids])
		subjects.each do |subject|
			@student.subjects << subject
		end

		if @student.save
			redirect_to zno_students_path
		else
			render 'new'
		end
	end
	def edit
		@subjects = Subject.all
		@student = Student.find params[:id]
	end

	def update
		@student = Student.find params[:id]
		@student.update student_params
		@student.semester = @semester.name
		subjects = Subject.where(id: params[:subject_ids])
		subjects.each do |subject|
			@student.subjects << subject
		end
		if @student
			redirect_to zno_students_path
		else
			render 'edit'
		end
	end

	def index
		unless params[:student_ids]
			@students = Student.where(grade: "11", semester: @semester.name)
			@subjects = Subject.all
			@student_ids = @students.map {|s| s.id }
		else
			@students = Student.where(id: params[:student_ids])
			@subjects = Subject.all
			@student_ids = params[:student_ids]
		end
	end

	def show

	end

	def filter
		if params[:subject][:id].present?
			@students = Student.joins(:subjects).where("grade = ? and semester = ? and subjects.id = ?","11", @semester.name, params[:subject][:id])
			@student_ids = @students.map { |s| s.id }
		else
			@students = Student.where(grade: "11")
			@student_ids = @students.map {|s| s.id }
		end
		@subjects = Subject.all
		render 'index'
	end

	def delete
		@student = Student.find(params[:student_id])
	end

	def destroy
     	@student = Student.find(params[:id])
     	@student.destroy
     	redirect_to zno_students_path(student_ids: params[:student_ids])
	end

	def xls_index
		package = Axlsx::Package.new
   		workbook = package.workbook
    	@students = Student.where(id: params[:student_ids])
    	workbook.add_worksheet(name: "Студенты") do |sheet|
     		sheet.add_row ["ФИО Студента", "Email", "Адрес", "Skype","Телефон","Школа" ,"Предметы"]
     		@students.each do |s|
     			subjects = s.subjects.map { |s| s.title}.join(", ")
        		sheet.add_row [s.full_name, s.email, s.address, s.skype ,s.phone, s.school, subjects]
      		end
    	end
    	package.serialize "Basic.xlsx"
    	send_file("#{Rails.root}/Basic.xlsx", filename: "Basic.xlsx", type: "application/vnd.ms-excel")
	end

	protected 
		def student_params
			params.require(:student).permit(:first_name, :last_name, :email, :phone, :address, :school, :skype)
		end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/distant/students/edit.html.erb
<%= render 'distant/layouts/sidebar' %>

<div class="student-form" >
<%= form_for @student, url: {controller: "distant/students" ,action: "update"} do |f| %>
	<%= f.label "Имя" %>  
    <%= f.text_field :first_name %>
	<%= f.label "Фамилия" %>  
    <%= f.text_field :last_name %>
    <%= f.label :email %>  
    <%= f.text_field :email %>
    <%= f.label "Телефон" %>  
    <%= f.text_field :phone %>
    <%= f.label "Домашний адрес" %>  
    <%= f.text_field :address %>
    <%= f.label "Школа" %>  
    <%= f.text_field :school %>
    <%= f.label "Класс" %>  
    <%= f.text_field :grade %>
        <%= f.label "Skype" %>  
    <%= f.text_field :skype %>
    <%= f.label "Предметы" %>
    <div class = "subject_box" >
    <ul class="two-col-special">
        <% @subjects.each do |subject| %>
            <li>
                 <%= h subject.title -%>
                <%= check_box_tag 'subject_ids[]', subject.id -%> 
            </li>
        <% end %>
    </ul>
     </div>
    <%= f.submit "Сохранить" %>
<% end %>
<div>

app/views/distant/students/index.html.erb
<%= render 'distant/layouts/sidebar' %>

<div class="content" >
	
	<div class="content-table" >
		<table>
			<thead>
		    <tr>
		      <th>ID</th>
		      <th>ФИО студента</th>
		      <th>email</th>
		      <th>Skype</th>
		      <th>Адрес</th>
		      <th>Телефон</th>
		      <th>Класс</th>
		      <th>Предметы</th>
		      <th></th>
		      <th></th>
		    </tr>
		  </thead>
		   <tbody>
				<% @students.each_with_index do |student, index| %>
				<tr>
   					<th><%= index +1 %></th>
					<td><%= student.full_name %></td>
					<td><%= student.email %></td>
					<th><%= student.skype %></th>
					<td><%= student.address %></td>
					<td><%= student.phone %></td>
					<td><%= student.grade %></td>
					<td class="subject-td"><%= student.subject_titles %></td>
					<td><%= link_to "редактировать", edit_distant_student_path(id: student.id) %></td>
					<td><%= link_to "удалить", distant_student_path(id: student.id, student_ids: @student_ids), method: :delete, data: { confirm: "Вы уверены?" } %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<div class="right-sidebar" >
	<%= form_tag({ controller: "students", action: "filter" }, method: :get) do %>
	  <%= label_tag "Предмет" %>

	  <%= collection_select :subject, :id, @subjects, :id, :title, prompt: "Все" %>
	  	  <br />
	  <%= submit_tag("Найти") %>
	<% end %>

	<%= link_to "Добавить студента", new_distant_student_path, class: "button small" %>
	<%= link_to "Excel", distant_xls_index_path(student_ids: @student_ids),  class: "button small" %>
</div>

app/views/distant/students/new.html.erb
<%= render 'distant/layouts/sidebar' %>

<div class="student-form" >
<%= form_for @student, url: {controller: "distant/students" ,action: "create"} do |f| %>
	<%= f.label "Имя" %>  
    <%= f.text_field :first_name %>
	<%= f.label "Фамилия" %>  
    <%= f.text_field :last_name %>
    <%= f.label :email %>  
    <%= f.text_field :email %>
    <%= f.label "Телефон" %>  
    <%= f.text_field :phone %>
    <%= f.label "Домашний адрес" %>  
    <%= f.text_field :address %>
    <%= f.label "Школа" %>  
    <%= f.text_field :school %>
    <%= f.label "Класс" %>  
    <%= f.text_field :grade %>
    <%= f.label "Skype" %>  
    <%= f.text_field :skype %>
    <%= f.label "Предметы" %>
    <div class = "subject_box" >
    <ul class="two-col-special">
        <% @subjects.each do |subject| %>
            <li>
                 <%= h subject.title -%>
                <%= check_box_tag 'subject_ids[]', subject.id -%> 
            </li>
        <% end %>
    </ul>
     </div>
    <%= f.submit "Сохранить" %>
<% end %>
<div>