config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"
  

  resources :semesters, only: [:new, :create ]

  namespace :zno do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  namespace :distant do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  devise_for :users

end

app/models/task.rb
class Task < ActiveRecord::Base
	has_attached_file :task_file
	has_many :task_reports
	validates :title, presence: true

	do_not_validate_attachment_file_type :task_file
end

app/controllers/distant/tasks_controller.rb
class Distant::TasksController < DistantController
  def new
  	@task = Task.new
  end

  def index
  	@tasks = Task.where(grade: "distant", semester: @semester.name)
  end

  def create
  	@task = Task.new task_params
    @task.grade = "distant"
    @task.semester = @semester.name
    @task.save
  	redirect_to  distant_tasks_path
  end

  protected

  	def task_params
 	 params.require(:task).permit(:title, :task_file)
	end
end

app/controllers/zno/tasks_controller.rb
class Zno::TasksController < ZnoController
  def new
  	@task = Task.new
  end

  def index
  	@tasks = Task.where(grade: "zno", semester: @semester.name)
  end

  def create
  	@task = Task.new task_params
    @task.grade = "zno"
    @task.semester = @semester.name
    @task.save
  	redirect_to  zno_tasks_path
  end

 
  protected

  	def task_params
 	 params.require(:task).permit(:title, :task_file)
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/index.html.erb
<table>
	<thead>
    <tr>
      <th>Название</th>
      <th>Создан</th>
    </tr>
  </thead>
   <tbody>
		<% @tasks.each do |task| %>
		<tr>
			<td><%= task.title %></td>
			<td><%= task.created_at %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Добавить задание", new_task_path, class: "button small task_button" %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
	<%= f.label "Название" %>  
    <%= f.text_field :title %>
	<%= f.label "Файл" %>  
    <%= f.file_field :task_file %>

    <%= f.submit "Сохранить" %>
<% end %>