config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"
  

  resources :semesters, only: [:new, :create ]

  namespace :zno do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  namespace :distant do
    get 'mails/index'
    post 'mails/send_mail'
    post 'mails/receive'
    get 'mails/send_task'

    

    resources :tasks
    resources :students
    resources :subjects

    controller :mails do
      get '/download_report', to: 'mails#download_report'
    end 

    controller :students do
      get 'xls_index'
      get 'filter'
    end

  end

  devise_for :users

end

app/views/layouts/_footer.html.erb
<footer class="row">
<div class="large-12 columns">
<hr/>
<div class="row">
<div class="large-6 columns">
</div>

</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header >
<%= link_to "Главная", root_path %>
<div class="right-header">
	<%= link_to "Семестр", new_semester_path %>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>ЦДО</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>ЦДО</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="row">
      <div class="large-9 push-3 columns">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>